# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
fast <- function(Xr, Gr, r = 5L, lambda_1r = 1.0, lambda_2r = 1.0, n_iter = 1000L, converge = 1e-6) {
    .Call(`_FAST_fast`, Xr, Gr, r, lambda_1r, lambda_2r, n_iter, converge)
}

